# Generated by GitHub Copilot on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
