# Generated by Django 6.0.3 on 2026-04-10 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_supervisorverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorLoginRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_token', models.CharField(max_length=255, unique=True)),
                ('session_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for Admin Approval'), ('approved', 'Approved - Can Login'), ('rejected', 'Rejected'), ('expired', 'Request Expired')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('device_info', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('department', models.CharField(default='General', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.DeleteModel(
            name='SupervisorVerification',
        ),
        migrations.AddField(
            model_name='supervisorloginrequest',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_requests', to='users.supervisorregistration'),
        ),
    ]
