# Generated by Django 6.0.3 on 2026-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supervisorloginrequest_supervisorregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
